name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@mcoloniab.com:22/mcoloniab'
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
